wpmetabox/meta-box

js/plupload-image.js
Exited early due to an extra double quote after RWMB.url concatenation.
=> fixed path to loader.gif for plupload-image

inc/field.php, inc/fields/wysiwyg.php
This change helps remove check for wysiwyg type fields in `RWMB_Field`
=> Separate escaping into a separate function

inc/fields/autocomplete.php, inc/helpers.php, js/autocomplete.js
* Improved autocomplete field: added ability to use URL resource to return JSON data instead of predefined options; 
* Improved autocomplete field: added ability to show excerpt instead of label for selected option.
* Added condition function_exists to prevent potential issue with redeclaration of functions in inc/helpers.php
Usage Example:
```php
// Field declaration
array(
'name' => 'Some Field',
'id' => 'some_field',
'type' => 'autocomplete',
'options' => admin_url( 'admin-ajax.php?action=some_field' ),
)
// Backend
add_action( 'wp_ajax_some_field', function(){
$s = $_REQUEST[ 'term' ];
// Do some stuff here to find matches.
// Example of excerption in response which is shown for selected option instead of label.
$response = array(
array( 'value' => '123', 'label' => 'Some Post', …
```
=> Added ability to use AJAX reponse instead of predefined options in Autocomplete Field

inc/fields/text.php
Text field values weren't being escaped but somehow this worked out fine for non-cloneable fields. However, with cloneable fields this could become an issue if the text contains a double quote.
Fixes #594
=> Add escaping for text field values

inc/fields/select.php
This simply resolves some "Use strict comparisons (=== or !==)" WordPress-Coding-Standards phpcs warnings (WordPress.PHP.StrictComparisons).
=> Use strict comparisons in select.php file

inc/fields/autocomplete.php, inc/fields/date.php, inc/fields/datetime.php, inc/fields/map.php, inc/fields/plupload-image.php, inc/fields/select-advanced.php, inc/fields/slider.php, inc/fields/time.php, inc/fields/wysiwyg.php
This fixes the "The use of function `json_encode()` is discouraged; use `wp_json_encode()` instead" WordPress-Coding-Standards phpcs warnings (WordPress.PHP.DiscouragedFunctions.DiscouragedWithAlternative).
From what I've seen, `wp_json_encode()` is a drop-in replacement for `json_encode()` in these instances but you may want to test everything before merging this, of course.
=> Use wp_json_encode() instead of json_encode()

composer.json
The `"minimum-stability": "dev"` option forces all packages that use this project as dependency has the same `minimum-stability` setting.
=> Changed minimum-stability to stable

inc/fields/image.php
I've added new `srcset` attribute in WP4.4. 
I've tried to add `'sizes' => wp_get_attachment_image_sizes( $file_id ),` but it seems to return default value.
=> Please add 'srcset' for images.

inc/fields/taxonomy.php
After updated one of my sites to meta-box 4.8.2 (from 4.7.3), almost everything went smooth.
I only had a warning when retrieving a postmeta of type taxonomy.
> Warning: reset() expects parameter 1 to be array, boolean given in /Users/username/Sites/mysite.local/dev/wp-content/plugins/meta-box/inc/fields/taxonomy.php on line 144
To fix it, an `is_array` conditionnal prevents `$value` to be reset if it's not an array
=> Fix warning get_value of taxonomy field

css/select.css
Min width for type select to match the width of text input.
> ![](https://i.imgur.com/NlG6WYu.png)
> ![](https://i.imgur.com/aKB7Yxk.png)
=> Adds min-width to type `select`

inc/field.php, inc/fields/taxonomy-advanced.php, inc/fields/taxonomy.php, inc/meta-box.php
- Created `raw_meta` function to pull raw meta without formatting
- Use `raw_meta` to replace calls to `get_post_meta`
- Create versions of `raw_meta` for `taxonomy` and `taxonomy_advanced`
to reuse `meta` function
Fixes issue https://github.com/rilwis/meta-box/issues/988 that prevented
meta boxes with only taxonomy fields from being seen as saved.
=> Refactored meta code

inc/fields/input.php
Email field appears shorter than other fields ( for example text and url fields ). I tried to fix that in this commit. Please do it in a better way if possible as I am not confident about this improvement.
=> Fixed shorter width of email field VS other fields

inc/wpml.php
Correct condition so that the fields based on posts/taxonomies are correctly translated.
=> Correct condition so that the fields are correctly translated.

js/date.js
I found a bug where if an inline calendar is being used, and the user tries to clear the date input field when there is already an entered date, the field would auto-fill to today's date.
Could you possibly include this in the next plugin update release?
Thanks!
=> Update date field to allow empty string input

inc/meta-box.php
added field filter to allow the $field object to be modified before saving meta. Useful if a user does not have rights to make changes, but can submit changes for review.
=> added filter for $field

codesniffer.ruleset.xml, inc/fields/button-group.php, inc/fields/choice.php, inc/fields/input-list.php, inc/fields/object-choice.php, inc/fields/post.php, inc/fields/select-tree.php, inc/fields/select.php, inc/fields/sidebar.php, inc/fields/taxonomy.php, inc/fields/user.php, inc/walkers/base.php, inc/walkers/input-list.php, inc/walkers/select-tree.php, inc/walkers/select.php
Optimize object fields (post, user, taxonomy):
- Do not perform any extra query for clones. Only one query when fields are initialized.
- Reduce complexity in walkers and how fields call walkers to set label & value
=> Optimize object fields (post, user, taxonomy)

inc/meta-box.php, inc/storages/base.php
When is adding new post (any type) then is_saved() is always returned as true.
It is behavior of https://codex.wordpress.org/Function_Reference/get_metadata because every new post is autosaved, it has an ID in autosave state. get_metadata returns always empty string for non-existed key. False is returned only when object_id and meta_type doesn't exists. It never happens.
But WP has helper function to check if key really exists https://developer.wordpress.org/reference/functions/metadata_exists/
=> Fix is_saved() when creating new post

css/taxonomy.css, inc/fields/object-choice.php, inc/fields/taxonomy-advanced.php, inc/fields/taxonomy.php, js/taxonomy.js
Adds a button link "Add new term" to `taxonomy` and `taxonomy_advanced` fields. When click that button, shows the input for entering new term name.
Requires `'add_new' => true`.
Limitation:
- Not working inside group.
- Not working for cloneable fields.
=> Allows to add new term for `taxonomy` and `taxonomy_advanced` fields

inc/fields/osm.php
Enqueue missing style and script for jQuery autocomplete for the Open Street Maps address field
For more information, see issue at: https://metabox.io/support/topic/osm-map-with-user-meta-error-address-autocomplete-is-not-a-function/
=> Added required jQuery autocomplete to the osm field

inc/fields/image-advanced.php, inc/fields/media.php, js/media.js
Media fields load saved attachments via ajax requests. If a post has a lot of media fields or clones, the number of ajax requests is high and can cause server down.
This PR removes such ajax requests and uses PHP to get attachment data and outputs in the HTML for later use by JS. This method, however, increase the number of queries to the database. But overall, in our test, the performance increases.
See this discussion:
https://metabox.io/support/topic/input-type-image_advanced-vs-image/
=> Remove initial ajax requests to get attachments for media fields

js/media.js
This is just a possible fix for the bug that clears images in the image_advanced field when the media library is opened from within the Gutenberg editor.
=> media.js fix for Gutenberg bug

js/media.js
Since the first fix used the `components-button` css class as a conditional, it did not take into account Gutenberg blocks with media upload functionality outside of WordPress core.
In this update, the conditional check uses attributes set by the MB plugin. This way, we don't remove models unless the remove was triggered by the MB plugin.
I am guessing the first fix did not work for the forum topic linked below because the media upload blocks were built custom and do not include any reference to the `components-button` css class.
https://metabox.io/support/topic/gutenberg-sidebar-media-upload-clash-with-image_advanced/
=> Update media.js fix for Gutenberg bug

inc/about/about.php
#1325 
The second argument $network_wide is not set to false by default, so when we use the action activated_plugin it launches the action from RWMB_About and try to redirect, but it generates a Fatal Error because the second argument is not defined.
=> Fatal error with RWMB_About::redirect()

inc/clone.php, inc/fields/file.php, js/file.js
Each file upload (clone or non-clone) now has an unique file upload key, allowing to access to `$_FILES` directly, allowing to handle file upload and clone easily in normal fields and in groups.
=> Improve file upload

js/validate.js
There is a case I need to hide a field using Meta Box Conditional Logic and set it as required, and the validation should executed only when the field is visible.
=> Fixing validation rules still applied for hidden fields

inc/meta-box.php
Removed redundant and unused `after_save_field` hook parameter
=> Code clean-up

inc/autoloader.php
@rilwis how's it going? Recently when I was debugging a server with Redux 4 I found this issue. Namely on some servers (especially with apache it seems) if the local is set in a different language some characters won't go lowercase which causes such pain with autoloaders.
Basically I fixed the issue in our code and found your class (which the user's environment was using) had the same issue.
So I'd suggest you do as I just did and do a mass search and replace for `strtolower()` to `mb_strtolower()`.
Hope all is well!  :)
=> strtolower() fails in some environments

inc/autoloader.php
this missing semicolon currently breaks our staging environment
=> fix autoloader.php

css/wysiwyg.css, inc/fields/wysiwyg.php, js/clone.js, js/wysiwyg.js
- Fix editor blank in Gutenberg
- Fix content in the visual tab not saving
What is done:
- Re-render editors in Gutenberg editor, don't re-render in classic editor.
- While re-render, respect default editor mode (which can be set via a filter).
- Apply re-render after reorder editors, or groups that contain editors.
- Update the fix for validation, e.g. required rule now working for editors as well.
=> Fix editor

.gitignore, inc/field.php, inc/fields/osm.php, js/clone.js
Added the ability to set clone_min attribute that toggles the remove-clone buttons off when the list is at the defined minimum value (not just one).
Updated the leaflet library to 1.7.1 from the outdated 1.5.1 version.
Updated the .gitignore file to also igmore .DS_Store files from MacOS devices.
=> Clone Minimum & Updated Leaflet Library

inc/templates/media.php
Many non-image file types may provide image thumbnails in WordPress. The most common example may be 'application/pdf' which often generates thumbnail images that WP uses as icons for these files. WP reports these images in `data.sizes` when doing the `wp_prepare_attachment_for_js()` that these "File Advanced" elements use (in /inc/fields/media.php) to generate the data that this template then renders. By requiring a type of `'image'` before allowing a check for `data.sizes`, Meta Box currently is forced to render a dull and uninformative icon for PDF files, even when a better image was supplied in `data.sizes`. 
Why not trust WordPress? If it supplies `data.sizes` we should use it regardless of the mime type! I propose we remove this test for `'image' === data.type` use `data.sizes` …
=> Remove 'image' type requirement for thumbnails

inc/fields/post.php
From time to time consumers of Meta Box need to modify the query that Meta Box initiates in line 127 of this file. This is easy enough to do using various WordPress filters, such as the `posts_clauses` filter. However, it can be difficult to identify which queries belong to Meta Box. Our method to date has been to add a special query variable when defining a given field. But this is tedious and a bit error prone.
This change would provide such a `mb_field_id` query variable automatically, ensuring that developers could check for that variable and it's value before they modify any given query with WP filters.
For example, we have a use case where we need to add a prefix and suffix to the title values normally searched by the Select Advanced field. We add these by modifying the `'join'` and …
=> Provide MB field ID in query variable args

inc/fields/post.php
So sorry about that! I actually edited this one in GitHub itself and didn't realize I'd introduced a typo. My apologies!
=> Fix syntax error in mb_field_id

inc/fields/post.php
Added new 'rwmb_ajax_results' filter to allow developers to modify the returned AJAX results, allowing for things like 'Add new Item' to be appended to the results.
Example of how this would be used:
```
add_filter( 'rwmb_ajax_results', 'modify_ajax_results', 10, 3 );
function modify_ajax_results( $results, $field, $request ) {
if ( 'venue' == $field['id'] ) {
$create_new_option = array(
'value' => 'create_new_vanue',
'label' => '+ Create New',
);
array_push( $results, $create_new_option );
}
return $results;
}
```
=> Added the rwmb_ajax_results filter

inc/fields/file-upload.php, inc/fields/image-advanced.php, inc/fields/media.php, inc/fields/video.php
This PR fix the root cause of missing media templates [caused by Elementor](https://github.com/elementor/elementor/issues/23390) and WP 6.3.
The problem is that Elementor calls `wp_print_media_template()`, which Meta Box uses to output media templates. However, in WP 6.3, WP gathers all styles and scripts to use in the block editor. Because Meta Box used `require_once`, the media templates are outputted once when Elementor calls `wp_print_media_template()`, and are gathered. Changing it to `require` makes the templates display as they should be.
This PR is the final fix for this series:
- https://github.com/wpmetabox/meta-box/commit/109f748f08f19013acd847165387796a7f82296f
- https://github.com/wpmetabox/meta-box/commit/c27138c986ddf69a5bf1320c53391c5771bb090a
- …
=> Fix media templates missing in blocks

inc/fields/autocomplete.php, js/clone.js
This commit 
- fixes autocomplete when options have no key (starts at 0), it selects the first value by default.
- fixes clone.js when runs via ajax
```php
[
'id' => 'autocomplete',
'name' => 'Autocomplete',
'type' => 'autocomplete',
'options' => [
'Apple',
'Orange',
'Banana',
],
'clone' => true,
]
```
=> fix: autocomplete and ajax clone.js

inc/fields/autocomplete.php
This issue is related to JQuery UI treating the first element of array differently.
we have an array like:
```
['Foo', 'Bar', 'Baz']
```
If we select 'Bar' or 'Baz', `ui.item.value` returns 1 or 2, but if we select 'Foo', it returns its label instead of actual value, in this case, it returns 'Foo' instead of 0. So, the value returned is wrong.
=> fix: cannot save first value of autocomplete

inc/functions.php, inc/shortcode.php
Changes:
Shortcodes are now output safe html by default:
Example:
```
[rwmb_meta id="icon"]
```
To output unsafe html
```
add_filter('rwmb_meta_shortcode_secure', '__return_false');
OR
add_filter('rwmb_meta_shortcode_secure_icon', '__return_false');
```
=> Security sanitize output

js/modal.js, js/post.js, js/taxonomy.js, js/user.js
Admin notices are displaying wrong when removing elements, so we need to hide instead of remove
https://wordpress.stackexchange.com/questions/220650/how-to-change-the-location-of-admin-notice-in-html-without-using-javascript
=> style: hide() instead of .remove()

css/modal.css, js/modal.js, js/taxonomy.js, js/user.js
Ngoài revert ra e còn fix 1 số lỗi nhỏ nữa, ví dụ như trong `user.js` và `taxonomy.js` mình set css width cho modal, tuy nhiên dùng `.css()` như thế thì modal sẽ bị set luôn css đó và khi mở lại modal `post` sẽ bị size nhỏ như `user` và `taxonomy`, do vậy e thêm 1 config là size, mặc định sẽ là `large`.
E set size vào attribute thay vì class vì như vậy code sẽ gọn hơn, thay vì remove class rồi add class thì chỉ cần set attribute thôi.
=> revert: use div instead of dialog

js/modal.js
E phát hiện ra 1 lỗi nhỏ là khi set attribute `url` thì URL trong modal không được update. Nguyên nhân là do `$.data('url')` bị cache. Mình dùng `$.attr('data-url')` thì sẽ không bị cache nữa.
=> fix(modal): url's attribute not updated

inc/fields/post.php, inc/fields/user.php
E thấy term sẽ visible với tất cả user nên e không fix, không biết có trường hợp nào cần limit không?
Hướng xử lý của e:
- Thêm `perm` vào query, mặc định là `readable`.
- Không chấp nhận query `perm` qua ajax.
- Ẩn `user_email` và `user_pass`.
- Không chấp nhận query `fields` qua ajax.
- Nếu người dùng vẫn muốn lấy `user_email` thì dùng filter như sau:
```
// This filter accepts two paramters
add_filter ('rwmb_user_query_args_fields', function ($args, $field) {
return [
'ID',
'user_login',
'user_email',
'user_nicename',
'user_url',
'user_registered',
'user_status',
'display_name',
];
}, 10, 2);
```
P/S: Thực ra e thấy config `fields` qua settings của field hay hơn là dùng filter, nhưng trong phần ajax làm sao lấy được $field qua field id nhỉ? Dùng `$field = rwmb_get_field_settings( …
=> Fix broken access control

inc/fields/post.php
Latest fix with `'perm' => 'readable'` doesn't work because when we set 'post_status' => 'any-string', it still shows private posts.
Need to check each post with `current_user_can()` function.
For password protected posts, user can still read the title so it should return data and it isn't bug.
=> fix: wp query perm

inc/field.php
Resolve issues arising from the use of sprintf which led to fatal errors when handling special characters like `%` in field contents.
1. Removed `sprintf`:
- Replaced with direct string concatenation to enhance control and prevent format specifier errors.
2. Escaping and Concatenation:
- Escaped class attributes using esc_attr to ensure security.
- Concatenated strings directly to form the final HTML output, ensuring that special characters in dynamic content do not disrupt the output.
Prior implementation using sprintf caused fatal errors when special characters interfered with format specifiers.
Direct string concatenation mitigates these issues, providing a more robust method for generating HTML while maintaining the ability to filter content at various stages.
Manually tested with …
=> Replace sprintf with String Concatenation in RWMB_Field::show

inc/clone.php
Bản update trước, trường hợp clone index = 0 (template) hoặc 1 (original id) thì mình sẽ khai báo bằng `$field['id'] . _rwmb_template` hoặc `$field[id]`.
Tuy nhiên, làm vậy chưa đúng với trường hợp cả group + subfield đều clone, như vậy nó sẽ trở thành:
- groupId_template
-- subfieldId_rwmb_template
-- subfieldId
- groupId
-- subfieldId_rwmb_template
-- subfieldId
Như vậy là bị trùng lặp ID dẫn đến wysiwyg init bị sai.
Cách sửa là ta dùng $field['attributes']['id'] thay vì $field['id'] vì trong group mình đã xử lý phần này tốt rồi.
=> fix: subfield's id

js/validation/validation.js
By default, our validation prevents form submitting using onsubmit event, but WP use button.onclick event so validation doesnt work for taxonomy form.
This PR add the ability to disable Add New Taxonomy button until the form is validated.
=> feat: validation for taxonomies

js/clone.js, js/validation/jquery.validate.js, js/validation/validation.js
When `settings.ignore` enabled, there are some elements that should not be validated, jquery.validate did ignore it in `validationTargetFor()` method but the caller still continue running that function. This causes run time error, `element.type` or `element.value` not exists because `element` is undefined.
=> fix: validation error when element not found

js/map.js, js/osm.js
support osm autocomplete inside group
=> feat: osm autocomplete inside group

inc/field.php
Previous version, if max clone = 1, then we remove clone attribute and treat as noncloneable field.
But when clone empty start = true, we should support max clone = 1, since it starts with zero field.
This commit fixes that issue.
Tested with clone and not clone field, clone empty start and not empty start field.
https://app.asana.com/0/1204192622667775/1209132788111951
=> fix: max clone with clone empty start

inc/field.php
The previous PR added support max_clone = 1, to do that, I removed $field['max_clone'] = 1 check
https://github.com/wpmetabox/meta-box/commit/263fd9a7f13e79dfdb57a3a6e1538b642f83246a
But the data from the builder is always has max_clone = 0 by default, so `is_numeric( $field['max_clone'] )` is always true, therefore the html always printed out `data-max-clone=0` by default.
Thats why we always capped the limit, and the clone button doesnt show up.
Related: https://app.asana.com/0/inbox/1204192622667771/1209433895846414/1209434040753534
=> fix: min max clone from builder

inc/meta-box.php
The problem is `RW_Meta_Box::enqueue()` is called on the frontend via `enqueue_block_assets` action, which checks the current screen. In term meta's `MetaBox.php` class, `get_current_screen()` is not available (as it's for admin only).
This fix makes the `enqueue_block_assets` hook runs only in the admin, as its purpose is for previewing front-end forms and blocks. And both front-end forms and blocks already call the `enqueue()` method on the front end, so no need to hook to run it on the front end.
=> Fix get_current_screen() error for term meta
