wpmetabox/meta-box

inc/fields/autocomplete.php

Related Pull Request: https://github.com/rilwis/meta-box/pull/574
Added filter 'rwmb_autocomplete_result_label' to have ability to render custom HTML for .rwmb-autocomplete-results block on using AJAX instead of predefined options.

Improvements to Autocomplete field

---

inc/fields/datetime.php
js/date.js
js/datetime.js

Fixes for empty dates

---

inc/core.php
inc/wpml.php

* Add WPML compatibility class
(ID translation for post and taxonomy_advanced field types)
* Add get_fields() function for all registered fields retrieval

Add WPML compatibility

---

inc/loader.php

fixed check when meta-box is embedded in a theme with a symlinked folder

---

demo/map.php

Update Demo map.php to enlist API key param.

---

inc/clone.php

Solves https://github.com/rilwis/meta-box/issues/1014

check if $new is an array in the clone.php value()

---

js/file-upload.js

Fixes https://github.com/rilwis/meta-box/issues/1047

Fix bug with file upload

---

inc/fields/media.php
js/media.js

Also item view caching done by`_.memoize`

Fix bug with force_delete that caused files to be deleted

---

inc/fields/input-list.php
js/input-list.js

This would add a button for "Check/Uncheck all options" when input field list is a checkbox_list

Added button for "Check/Uncheck all options"

---

css/datepicker.css

Brought Date picker in front of admin bar

---

inc/field.php

Based on this discussion #1215

Save cloned fields as multiple values (each row in database)

---

inc/about/about.php

Prevent warning when plugin activated via wp_cli

fix(activation): fix warning when installed via wp-cli #1248

---

js/media.js

I tested it and seems to work, but I don't know Backbone.js well so it should be double checked.

Fix #1265 getting models from "this" instead of options object

---

js/autosave.js

[issue](https://github.com/wpmetabox/meta-box/issues/1269)

check if passed data is array before calling indexOf in ajaxSend

---

inc/fields/post.php
inc/fields/taxonomy.php
inc/fields/user.php
inc/walkers/input-list.php
inc/walkers/select.php

Restore missing choice_label filter

---

inc/functions.php

First commit to get assoc array fields for object

Get object fields

---

js/media.js

Updated fix, attempts to solve bug still present for user in topic below:
https://metabox.io/support/topic/gutenberg-sidebar-media-upload-clash-with-image_advanced/

Update media.js fix for Gutenberg bug

---

css/autocomplete.css
css/date.css
css/select-advanced.css
inc/fields/datetime.php
inc/fields/file.php
inc/fields/image-select.php
inc/fields/oembed.php
inc/fields/post.php
inc/fields/taxonomy.php
inc/fields/user.php
inc/functions.php
inc/meta-box.php
inc/request.php
inc/update/checker.php
inc/update/settings.php
inc/wpml.php
js/color.js
js/notification.js
js/script.js
js/wysiwyg.js

Also:
- Delay color picker to trigger change event
- Fix JQMIGRATE: `ready` event is deprecated
- Fix date picker, autocomplete, select2 not showing in the Customizer
- Add a custom trigger to reinitialize editors
- Fix undefined index for `image_select` field
- Make `object_id` property public

Add request object to get/set request params

---

inc/field-registry.php

Add a hook to pass field registration info to external plugins.
Fixes #1345

add rwmb_field_registered

---

inc/functions.php

#1366 raised to look into the possibility of this
Would love to hear thoughts and feedback on naming and how I am doing things. This is mostly pulled from the REST API plugin. I am not sure of the safety of calling `rwmb_get_storage` where I am but I don't know the codebase well enough.

add rwmb_set_meta

---

inc/field.php

MB Group: correct the label for subfield: https://app.asana.com/0/17125277541504/1200557165484686

Fix Bug MB Group: correct the label for subfield

---

inc/fields/map.php
js/map.js

https://app.asana.com/0/17125277541504/1201923344611240

Fix Field Google map: incorrect search

---

js/image-upload.js

https://app.asana.com/0/17125277541504/1202098197340606

Fix field image_upload not working with tab

---

css/media-modal.css
inc/fields/wysiwyg.php
inc/media-modal.php
inc/meta-box.php

https://app.asana.com/0/17125277541504/1202120201556027

Custom fields for CPT attachment: not showing value

---

inc/update/checker.php
inc/update/settings.php

- Use another endpoint API to get updates (via REST API)
- Use JSON instead of serialized data
- Cache requests for one day

Improve the updater

---

js/select-advanced.js

https://app.asana.com/0/17125277541504/1202127067906762

Fix select advanced don't escape HTML characters

---

inc/fields/button-group.php

https://app.asana.com/0/17125277541504/1199872843111879

Button Group option horizontally not save

---

inc/helpers/field.php

This makes it possible to overwrite the class used for a specific field type

Make field class filterable

---

inc/validation.php

I see that I made a mistake in the JS path, sorry.

Use correct JS path for localized validation files

---

js/map.js
js/osm.js

This PR will ask users for permission to access the current location via Geolocation API, which is available in all browsers and use that location to set the current map center and for the marker.
Previously, the plugin always loads the Dublin location as default, which causes a confusion for users in other countries.
This "ask" won't happen if there's a saved location, or a default location. In other words, it only asks if there's no location is saved or set as default.

Google Maps & OSM: ask for current user location for the map

---

css/modal.css
js/modal.js
js/post.js
js/user.js

- Remove unused variable so other pages can reuse this modal
- Use `<dialog>` tag, support `esc` key, click outside
- Fix add new post doesn't works

refactor: remove unused variable

---

js/validation/validation.js

- feat: Add validations with blocks
- fix: Validation error in WP 6.6

feat: validation with blocks

---

css/style.css
inc/clone.php
inc/field.php
js/clone.js
phpcs.xml
tests/020-clone-empty-start.php

if `clone_empty_start=true`, only show the "Add New" button

feat: allows clone from empty

---

inc/walkers/select-tree.php

Fix lỗi attribute required true not works

Bỏ required ở các field con

---

js/validation/validation.js

https://app.asana.com/0/inbox/1204192622667771

Fix validation for dash ids

---

js/osm.js

https://app.asana.com/1/11768486970802/project/17125277541504/task/1209236680708582?focus=true

Fix OSM not fully render with conditional logic
